### PR TITLE
Treat errors on repeated runs gracefully

### LINKED ISSUE #470: Treat errors on repeated runs gracefully
**Describe the bug**

When the action is run multiple times, it generates comments with error messages, even though all is good.

**To Reproduce**
1. Set up the action to trigger on an already merged PR's `label` event.
2. Add two backport labels at the same time (this results in *two* label events from GitHub :/)
3. See the action running two times and posting unhelpful comments.

Alternative: Add labels one at a time. Running the action the second time, will try to create the *first* PR again - throwing the same errors.

**Expected behavior**

The backport action should just detect already existing branches and PRs, ignore them and keep going.

**Workflow run logs**

<details><summary>Workflow run logs</summary>
<p>

```
 Retrieve pull request data for #412688
Check whether pull request 412688 is merged
Determining target branches...
Detected labels on PR: 8.has: port to stable,10.rebuild-darwin: 0,10.rebuild-linux: 0,backport release-24.11,backport release-25.05
label '8.has: port to stable' doesn't match `label_pattern` '^backport ([^ ]+)$'
label '10.rebuild-darwin: 0' doesn't match `label_pattern` '^backport ([^ ]+)$'
label '10.rebuild-linux: 0' doesn't match `label_pattern` '^backport ([^ ]+)$'
Found target branches in labels: release-24.11,release-25.05
Found target branches in `target_branches` input: 
Exclude pull request's headref from target branches: ci-workflow-ci-owners
Determined target branches: release-24.11,release-25.05
Fetching all the commits from the pull request: 2
git fetch --depth=2 origin refs/pull/412688/head
From https://github.com/NixOS/nixpkgs
 * branch                refs/pull/412688/head -> FETCH_HEAD
Retrieving the commits from pull request 412688
PR was merged using a merge commit
Found commits to backport: b98e7bb95a1e66d951a9c517cadb151694358bad
Checking the merged pull request for merge commits
git rev-list --merges b98e7bb95a1e66d951a9c517cadb151694358bad^..b98e7bb95a1e66d951a9c517cadb151694358bad
Encountered 0 merge commits
Will cherry-pick the following commits: b98e7bb95a1e66d951a9c517cadb151694358bad
Will copy labels matching /severity:\ssecurity/. Found matching labels: 
Backporting to target branch 'release-24.11...'
git fetch --depth=1 origin release-24.11
From https://github.com/NixOS/nixpkgs
 * branch                release-24.11 -> FETCH_HEAD
 * [new branch]          release-24.11 -> origin/release-24.11
Start backport to backport-412688-to-release-24.11
git switch -c backport-412688-to-release-24.11 origin/release-24.11
Warning: you are leaving 2 commits behind, not connected to
any of your branches:

  b98e7bb95 OWNERS: simplify workflow/ci owners
  9137f06a0 Xfce updates 2025-05-28 (#411782)

If you want to keep them by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> b98e7bb95

Switched to a new branch 'backport-412688-to-release-24.11'
git cherry-pick -x b98e7bb95a1e66d951a9c517cadb151694358bad
error: could not apply b98e7bb95... OWNERS: simplify workflow/ci owners
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
git cherry-pick --abort
Backport failed for `release-24.11`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
``bash
git fetch origin release-24.11
git worktree add -d .worktree/backport-412688-to-release-24.11 origin/release-24.11
cd .worktree/backport-412688-to-release-24.11
git switch --create backport-412688-to-release-24.11
git cherry-pick -x b98e7bb95a1e66d951a9c517cadb151694358bad
``
Create comment: Backport failed for `release-24.11`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
``bash
git fetch origin release-24.11
git worktree add -d .worktree/backport-412688-to-release-24.11 origin/release-24.11
cd .worktree/backport-412688-to-release-24.11
git switch --create backport-412688-to-release-24.11
git cherry-pick -x b98e7bb95a1e66d951a9c517cadb151694358bad
``
Backporting to target branch 'release-25.05...'
git fetch --depth=1 origin release-25.05
From https://github.com/NixOS/nixpkgs
 * branch                release-25.05 -> FETCH_HEAD
 * [new branch]          release-25.05 -> origin/release-25.05
Start backport to backport-412688-to-release-25.05
git switch -c backport-412688-to-release-25.05 origin/release-25.05
Switched to a new branch 'backport-412688-to-release-25.05'
git cherry-pick -x b98e7bb95a1e66d951a9c517cadb151694358bad
Push branch to origin
git push --set-upstream origin backport-412688-to-release-25.05
To https://github.com/NixOS/nixpkgs
 ! [rejected]            backport-412688-to-release-25.05 -> backport-412688-to-release-25.05 (fetch first)
Create comment: Git push to origin failed for release-25.05 with exitcode 1
error: failed to push some refs to 'https://github.com/NixOS/nixpkgs'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Git push to origin failed for release-25.05 with exitcode 1
```

</p>
</details> 

**Additional context**

PR here: https://github.com/NixOS/nixpkgs/pull/412688

Run: https://github.com/NixOS/nixpkgs/actions/runs/15632399147/job/44039593300

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Resolves #470

Before making the two main fixes, I had to fix error handling for API requests in general: Those octokit calls **don't** actually return a response with status code >=400 when the request fails. Instead they throw an error - so the second commit fixes that and handles the errors correctly.

After that, we can easily ignore "branch exists" or "PR exists" errors. We still keep going with the same target branch in the first case, because the PR creation might have failed in an earlier run. Thus, a subsequent run will then pick up where the first run left off and create the PR for the existing branch. It happened only very infrequently, but we observed some of those in nixpkgs.

I tested the changes in my fork: https://github.com/wolfgangwalther/backport-action/pull/1. After merge, you can see 3 `/backport` comments:
- The first one is with the published action and succeeds as expected.
- The second one is with the published action as well and fails - that's what we're trying to fix.
- The third one is with the local action (replaced `uses` in workflows/backport on main) - and with the new version, it stays silent.

The respective run is here: https://github.com/wolfgangwalther/backport-action/actions/runs/15794902201/job/44525673984

Relevant log output:

```
Push branch to origin
git push --set-upstream origin backport-1-to-stable
To https://github.com/wolfgangwalther/backport-action
 ! [rejected]        backport-1-to-stable -> backport-1-to-stable (fetch first)
error: failed to push some refs to 'https://github.com/wolfgangwalther/backport-action'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
git fetch --depth=1 origin backport-1-to-stable
From https://github.com/wolfgangwalther/backport-action
 * branch            backport-1-to-stable -> FETCH_HEAD
 * [new branch]      backport-1-to-stable -> origin/backport-1-to-stable
Create PR for backport-1-to-stable
Create PR: # Description
Backport of #1 to `stable`.
PR for backport-1-to-stable already exists, skipping.
```

We can see the fetch to confirm the branch exists (thus, the rejected push is ignored) and can see the PR creation being skipped because it already exists.

### CODE REVIEW

**Review by MattSturgeon — APPROVED** [review]
Control flow can be hard to follow, as is often the case when there's a lot of `try catch`, `continue`, etc jumps. But that's just the nature of JS, not a slight on the PR.

LGTM

File: src/backport.ts [hunk 1]
```diff
@@ -344,19 +344,30 @@ export class Backport {
...
-            });
-            continue;
+            try {
+              // If the branch already exists, ignore the error and keep going.
+              await this.git.fetch(
+                branchname,
+                this.config.pwd,
+                1,
+                this.getRemote(),
+              );
```
Comment (korthout) [inline src/backport.ts]: 💭 When this continues, it does not consider the case where the remote branch differs from the local branch. This introduces a risk to creating a PR for a branch that does not contain the contents created by the backport-action. However, it requires write access to the repo to push such a branch to the remote. We can thus consider it not dangerous. A potential future improvement would be verifying the branch's contents.

File: .editorconfig
Comment (korthout) [inline .editorconfig:1]: 👍 Thanks, I appreciate this addition

**Review by korthout — APPROVED** [review]
Thanks for this massive UX improvement @wolfgangwalther 🚀 I'm sure many teams using this action will be happy about these changes.

👍 I appreciate the error handling improvements

🔧 I agree with @MattSturgeon that the control flow could be improved. We can keep that out of scope of this PR, but I'm open to contributions to improve it.

💭 There's one note to make around security, as the remote branch's contents aren't verified. I believe this is okay because it requires write access anyways.

💭 I've added one commit to log a few more details about what's happening in the case where the branch already exists on the remote.

LGTM 👍
